### ISSUE TITLE
result screen

### ISSUE THREAD

**Issue by Stilic** [BeastlyGhost/FNF-BedrockEngine#24]
### What feature do you want to get added on the **base** engine?

the shit in the title
i will do it myself i think

### To test your sight, and reliability, please select the option of what should NOT be requested.

Extra Keys support

**Comment by Gui-iago** [comment]
https://github.com/Gui-iago/FNF-BedrockEngine/blob/main/source/ResultsScreen.hx

**Comment by flashintv** [comment]
CLOSE THE DAMN ISSUE ALREADY
