### ISSUE TITLE
Excessive Memory Usage

### ISSUE THREAD

**Issue by SteveeWasTaken** [BeastlyGhost/FNF-BedrockEngine#3]
### Describe your bug here.

Today, I downloaded a copy of the source code. I didn't edit anything in the source, just some images in the files, and compiled it. Once it was done compiling, I added a mod that works fine in normal Psych Engine, so I could play with "Opponent Play". But I noticed that as soon as the song was loaded, the memory usage would slowly rise up, until becoming excessively large. This makes the game completely unplayable. The memory usage was so ridiculously large it reached around 10-12GB. Please fix this as soon as possible!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing in Source Code, changed some images in the assets folder.

**Comment by Gui-iago** [comment]
that is a psych engine problem, there's some form of memory leak going on with leaving the game running at the background while **anything** loads, I'm gonna try to fix it but I can't guarantee it will be better than ShadowMario's solution

**Comment by SteveeWasTaken** [comment]
> that is a psych engine problem, there's some form of memory leak going on with leaving the game running at the background while **anything** loads, I'm gonna try to fix it but I can't guarantee it will be better than ShadowMario's solution
> 
> right now, check for lua scripts that might be loading with songs on the mods folder, enable Low Quality, Hide GF or Max Optimization, and just try to make it so the game uses less resources to avoid that kind of thing while I don't push an update to fix it
> 
> what I'd also recommend is to just download the builds from the Actions tab on github, github's virtual machines seem to compile the game without any errors, so downloading it from there might give you better results
> https://github.com/Gui-iago/FNF-BedrockEngine/actions
> NOTE: do not download debug builds, they are definitely going to give you more problems

i have noticed that this memory leak issue only happens if botplay is NOT enabled. if botplay is enabled, nothing happens. oh and also, this memory problem happens only when inside of a song, if you go back to the story menu / Freeplay menu, the memory usage comes back to normal

**Comment by SteveeWasTaken** [comment]
This bug was "Hopefully Fixed" but I still see it on the latest source code release...

**Comment by Gui-iago** [comment]
yeah I'm aware of the high memory usage, I'm currently trying to find the source of the problem so I can fix it, this also brought a shit ton of bugs

I might even consider rewriting the engine, because finding the source of the problem is just being complicated
